# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(468, 274)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 461, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.nameofproduct = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.nameofproduct.setObjectName("nameofproduct")
        self.gridLayout.addWidget(self.nameofproduct, 0, 1, 1, 1)
        self.countofproduct = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.countofproduct.setObjectName("countofproduct")
        self.gridLayout.addWidget(self.countofproduct, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.add = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setItalic(True)
        self.add.setFont(font)
        self.add.setStyleSheet("add{\n"
"    color: rgb(0, 170, 255);\n"
"}\n"
"\n"
"")
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 1, 1, 1, 1)
        self.delete_2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setItalic(True)
        self.delete_2.setFont(font)
        self.delete_2.setStyleSheet("delete_2{\n"
"    rgb(0, 170, 255)\n"
"}")
        self.delete_2.setObjectName("delete_2")
        self.gridLayout.addWidget(self.delete_2, 1, 2, 1, 1)
        self.listofproducts = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.listofproducts.setObjectName("listofproducts")
        self.gridLayout.addWidget(self.listofproducts, 2, 1, 1, 2)
        self.save = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 3, 1, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nazwa produktu"))
        self.label_2.setText(_translate("Dialog", "ilosc"))
        self.add.setText(_translate("Dialog", "Dodaj"))
        self.delete_2.setText(_translate("Dialog", "Usuń"))
        self.save.setText(_translate("Dialog", "Zapisz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
